[package]
name = "wtf-train"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
wtf-core = { path = "../wtf-core", features = ["counterfactual-replay"] }
