[package]
name = "wtf"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "wtf"
path = "src/main.rs"

[dependencies]
wtf-core = { path = "../wtf-core" }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
